
import { Preset, DisplayMode } from './types';

export const PRESETS: Preset[] = [
  {
    name: 'Matrix Green',
    settings: {
      headColor: '#ffffff',
      tailColor: '#00ff00',
      bgColor: '#000000',
      characterSet: 'katakana',
      fallSpeed: 5,
      fontSize: 20,
      glowEffect: true,
      ghostingEffect: false,
    },
  },
  {
    name: 'Hacker Mode',
    settings: {
      headColor: '#7fff00',
      tailColor: '#00ff00',
      bgColor: '#020f02',
      characterSet: 'js-code',
      fallSpeed: 9,
      fontSize: 16,
      randomization: 20,
      rainSpawnRate: 25,
      glitchChance: 1,
      enableMouseInteraction: true,
    },
  },
  {
    name: 'Digital Tsunami',
    settings: {
      headColor: '#ccddff',
      tailColor: '#0088ff',
      bgColor: '#020412',
      fallDirection: 'up',
      fallSpeed: 18,
      fontSize: 12,
      rainSpawnRate: 45,
      randomization: 80,
      characterSet: 'binary',
      glitchChance: 10,
    },
  },
  {
    name: 'Ghost in the Machine',
    settings: {
      headColor: '#ffffff',
      tailColor: '#aaaaaa',
      bgColor: '#0a0a0a',
      memoryMode: true,
      ghostingEffect: true,
      fadeOutRate: 0.03,
      fallSpeed: 2,
      glitchChance: 15,
      mode: DisplayMode.Sentences,
      enableBackgroundRain: false,
    },
  },
  {
    name: 'Code Red Emergency',
    settings: {
      headColor: '#ffffff',
      tailColor: '#ff2200',
      bgColor: '#100000',
      fallSpeed: 10,
      spawnFlash: true,
      volumeAffects: 'brightness',
      volumeSensitivity: 80,
      characterSet: 'numbers',
      glitchChance: 5,
      randomization: 90,
    },
  },
  {
    name: 'Vaporwave Dreams',
    settings: {
        headColor: '#ffffff',
        tailColor: '#ff69b4',
        bgColor: '#00003f',
        glowEffect: true,
        brightness: 9,
        fallDirection: 'up',
        fallSpeed: 3,
        characterSet: 'ascii',
        glitchChance: 8,
    }
  },
  {
    name: 'Frozen Core',
    settings: {
        headColor: '#e0ffff',
        tailColor: '#7df9ff',
        bgColor: '#0c1a2e',
        fallSpeed: 2,
        fontSize: 22,
        glowEffect: true,
        brightness: 6,
        characterSet: 'runes',
        rainSpawnRate: 8,
    }
  },
  {
    name: 'Golden Age',
    settings: {
        headColor: '#ffffe0',
        tailColor: '#ffd700',
        bgColor: '#1c1600',
        fallSpeed: 4,
        glowEffect: true,
        ghostingEffect: true,
        fadeOutRate: 0.08,
        characterSet: 'runes',
        brightness: 6,
    }
  },
  {
    name: 'Infrared',
    settings: {
        headColor: '#ffdd00',
        tailColor: '#ff0000',
        bgColor: '#1b002c',
        glowEffect: true,
        brightness: 10,
        volumeAffects: 'density',
        volumeSensitivity: 70,
        characterSet: 'binary',
        glitchChance: 15,
    }
  },
  {
    name: 'Psychedelic Glitch',
    settings: {
      headColor: '#ffff00',
      tailColor: '#00ffff',
      bgColor: '#0c0021',
      mode: DisplayMode.Words,
      glitchChance: 50,
      fallSpeed: 8,
      randomization: 100,
      characterSet: 'ascii',
      enableMouseInteraction: true,
      mouseEffectRadius: 200,
      mouseEffectStrength: -20,
    },
  },
  {
    name: 'Old Terminal',
    settings: {
      headColor: '#ffffbe',
      tailColor: '#ffb000',
      bgColor: '#1a1a1a',
      glowEffect: false,
      ghostingEffect: false,
      memoryMode: false,
      characterSet: 'ascii',
      fallSpeed: 3,
      brightness: 5,
      glitchChance: 1,
    },
  },
  {
    name: 'Synthwave',
    settings: {
      headColor: '#ffffff',
      tailColor: '#ff00ff',
      bgColor: '#2d004f',
      characterSet: 'js-code',
      fallDirection: 'up',
      glowEffect: true,
      brightness: 8,
      fallSpeed: 4,
    },
  },
];
